# Change these first
owner: grzchr15 # Your GitHub username
repo: uptime # Your Github repository name
user-agent: github-grzchr15
# Add your sites here
sites:
  - name: Google
    url: https://www.google.com
  - name: Wikipedia
    url: https://en.wikipedia.org
  - name: bretterhofer.at
    url: https://bretterhofer.at
  - name: h4.bretterhofer.at
    url: https://h4.bretterhofer.at/toggle.php
  - name: h6.bretterhofer.at
    url: https://h6.bretterhofer.at
  - name: volkstanz.st
    url: https://volkstanz.st
  - name: volkstanzwannwo.at
    url: https://volkstanzwannwo.at
  - name: kinderundjugendtanz.at
    url: https://kinderundjugendtanz.at
  - name: andritz.me
    url: https://andritz.me
#  - name: Secret Site
#    url: $SECRET_SITE

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  #cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Uptime
  introTitle: "**Uptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a status page which uses **real-time** data from our [Github repository](https://github.com/grzchr15/uptime). 
navbar:
    - title: Status
      href: /uptime
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
